---
#-----------------------
#  geerlingguy.haproxy
#-----------------------
haproxy_backend_servers:
  - name: demo
    address: 10.140.0.2:80
  - name: demo2
    address: 10.140.0.2:80

#-----------------------
#  geerlingguy.nginx
#-----------------------
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80"
    server_name: "example.com"
    root: "/var/www/html"
    index: "index.html index.htm"
    state: "present"
    # template: ""
    filename: "example.com.conf"
    extra_parameters: |
      # ssl_certificate       /etc/ssl/certs/ssl-cert-snakeoil.pem;
      # ssl_certificate_key   /etc/ssl/private/ssl-cert-snakeoil.key;
      # ssl_protocols         TLSv1.1 TLSv1.2;
      # ssl_ciphers           HIGH:!aNULL:!MD5;

      location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://127.0.0.1:5000;

        proxy_redirect off;
      }

#-----------------------
#  geerlingguy.mysql
#-----------------------
mysql_slow_query_log_enabled: true

#-----------------------
#
#-----------------------
app_env: develop
app_use_database: true
