---
- import_playbook: ping.yml

- name: install essential packages
  hosts: demo
  become: true
  roles:
    - server_setup

- name: setup database
  hosts: demo-db
  become: true
  roles:
    - geerlingguy.mysql

- name: setup haproxy
  hosts: demo-lb
  become: true
  roles:
    - geerlingguy.haproxy

- name: setup nginx
  hosts: demo-web
  become: true
  roles:
    - nginx_config
    - geerlingguy.nginx
    - app_setup
